#!/usr/bin/env bash

# install homebrew
if ! which brew > /dev/null 2>&1; then
  if [[ `xcode-select --version` ]] && [[ `which ruby` ]]; then
    echo "==> Instaling HomeBrew";
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" </dev/null;
    echo "==> Updating HomeBrew";
    brew update && brew cleanup;
    echo "==> Inspecting HomeBrew for configuration issues";
    brew doctor;
  else
    echo "==> Error: You need 'XCode Tools' to continue, please run 'xcode-select --install'";
    exit 1;
  fi
fi
# install brew-cask
if which brew > /dev/null 2>&1; then
  if ! brew ls | grep '^brew-cask$' > /dev/null 2>&1; then
    echo "==> Installing Brew-Cask"
    brew install caskroom/cask/brew-cask;
    echo "==> Updating Brew-Cask"
    brew cask update && brew cask cleanup;
    echo "== Inspecting Brew-Cask for configuration issues"
    brew cask doctor;
  fi
fi
# install taps
if which brew > /dev/null 2>&1; then
  if ! brew tap | grep -i -q "homebrew/completions" ; then
    echo "==> Installing homebrew/completions tap";
    brew tap homebrew/completions;
  fi
fi

# -- homebrew --
# install brew cask application in global /Applications directory
export HOMEBREW_CASK_OPTS="--appdir=/Applications";

# install virtualbox
if ! brew cask ls | grep "^virtualbox$" > /dev/null 2>&1; then
  echo "==> Installing VirtualBox"
  brew cask install virtualbox;
fi

# list vagrant plugins to be installed
vagrant_plugins=(
  "vagrant-berkshelf"
  "vagrant-omnibus"
  "vagrant-winrm"
);

# list vagrant boxes to be installed
vagrant_boxes=(
  "opscode_centos-6.7"
  "opscode_centos-7.1"
);

# install vagrant
if ! brew cask ls | grep "^vagrant$" > /dev/null 2>&1; then
  echo "==> Installing vagrant";
  brew cask install vagrant;
fi

# install vagrant plugins
for plugin in ${vagrant_plugins[@]}; do
  if ! vagrant plugin list | grep "^${plugin}\s.*$" > /dev/null 2>&1; then
    echo "==> Installing ${plugin}";
    vagrant plugin install ${plugin};
  fi
done

# install vagrant boxes
for box in ${vagrant_boxes[@]}; do
  if ! vagrant box list | grep "^${box}\s.*$" > /dev/null 2>&1; then
    echo "==> Installing ${box} vagrant box";
    vagrant box add --name ${box} https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/${box}_chef-provisionerless.box;
  fi
done

# install vagrant-completion
if brew tap | grep -i -q "homebrew/completions" && ! brew ls | grep -i -q "vagrant-completion"; then
  echo "==> Installing vagrant-completion";
  brew install vagrant-completion;
fi
